language: python

python:
  - "3.6"

script:
  echo " "
  
integrations:                               
  notifications:
    - integrationName: email
      type: email
      recipients:
        git --last_committer
	git --last_author
